#!/bin/python3
import subprocess
import os

def git_new():
    git = subprocess.Popen(
        'git diff --name-only --staged'.split(),
        stdout = subprocess.PIPE)
    details = git.stdout.read()
    details = details.decode('utf-8', 'replace').strip()
    return details
    
images = git_new().split('\n')
f = open(".commit", "w")

for image in images:
    if os.path.isfile(image):
        path = image.split('/')
        if path[0] == 'original':
            name = path[1].split('.')[0]
            new_image = 'images/{}.jpg'.format(name)
            subprocess.call(
                ['convert', '-resize', '400x400^', image,
                 '-background', 'white', '-flatten', '-alpha', 'off', new_image])
            f.write(new_image + "\n")
            print("creating {}".format(new_image))
f.close()
